# Generated by Django 2.0.6 on 2018-06-05 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4, null=True)),
                ('date', models.CharField(max_length=13, null=True)),
                ('category', models.CharField(max_length=200, null=True)),
                ('hand', models.CharField(max_length=5, null=True)),
                ('interval', models.CharField(max_length=10, null=True)),
                ('measurement', models.FloatField(null=True)),
                ('fraction', models.FloatField(null=True)),
            ],
        ),
    ]
