# Generated by Django 2.0.6 on 2018-06-05 00:52

import json
import os

from django.db import migrations

# Returns a list of the files, ignoring '.files', in the given directory
# Directory is a string of the path to the directory
def get_files(directory):
    files = os.listdir(directory)
    return [x for x in files if not (x.startswith('x'))]

def populate_temp_data(apps, schema_editor):
    directory = '../../data/E4/TEMP'
    files = get_files(directory)
    PhysData = apps.get_model('viz_app', 'PhysData')
    for tempFile in files:
        filenameElements = tempFile.split('_')
        participant = filenameElements[0]
        side = filenameElements[2]
        frequency = filenameElements[3][:-5]
        data = json.load(open(directory + '/' + tempFile, 'r'))
        for dateString in data["temp"]:
            temp = data["temp"][dateString]
            frac = data["fraction_of_measurements"][dateString]
            line = PhysData(date=dateString,
                            category="temp",
                            hand=side,
                            interval=frequency,
                            name=participant,
                            measurement=temp,
                            fraction=frac)
            line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_temp_data)
    ]
