# Generated by Django 2.0.6 on 2018-06-05 19:47

import datetime

from django.db import migrations, models
from dateutil import tz
from django.utils import timezone

def change_date_string_to_datefield(apps, schema_editor):
    PhysData = apps.get_model('viz_app', 'PhysData')
    for line in PhysData.objects.all():
        old_date = line.date    # string in database
        new_date = datetime.datetime.fromtimestamp(int(old_date)/1000)  # convert to datetime
        new_date = timezone.make_aware(new_date, tz.gettz('EST'))       # switch to correct timezone
        line._date = new_date
        line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0005_auto_20180605_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='physdata',
            name='_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.RunPython(change_date_string_to_datefield),
        migrations.RemoveField(
            model_name='physdata',
            name='date',
        ),
    ]
