# Generated by Django 2.0.6 on 2018-06-05 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0006_physdata__date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='physdata',
            old_name='_date',
            new_name='date',
        ),
    ]
