# Generated by Django 2.0.6 on 2018-07-23 22:03

from django.db import migrations


def change_category_strings(apps, schema_editor):
    conversion = {
        "acc": "Accelerometer",
        "hr": "Heart Rate",
        "motion": "Motion",
        "temp": "Temperature"
    }
    PhysData = apps.get_model('viz_app', 'PhysData')
    for line in PhysData.objects.all():
        line.category = conversion[line.category]
        line.save()

class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0007_auto_20180605_2040'),
    ]

    operations = [
        migrations.RunPython(change_category_strings)
    ]
