# Generated by Django 2.0.6 on 2018-08-01 19:08

from django.db import migrations
from ..value_mappings import *

def trim_error_data(apps, schema_editor):
    PhysData = apps.get_model('viz_app', 'PhysData')
    for line in PhysData.objects.all():
        data_type = line.category
        bounds = MEASUREMENT_THRESHOLDS[data_type]
        if line.measurement is not None and (line.measurement < bounds[0] or line.measurement > bounds[1]):
            line.measurement = None
            line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0009_auto_20180801_1808'),
    ]

    operations = [
        migrations.RunPython(trim_error_data)
    ]
