# Generated by Django 2.0.6 on 2018-08-19 14:46

from django.db import migrations


def delete_all(apps, schema_editor):
    PhysData = apps.get_model('viz_app', 'PhysData')
    PhysData.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0010_auto_20180801_1908'),
    ]

    operations = [
        migrations.RunPython(delete_all)
    ]
