# Generated by Django 2.0.6 on 2018-08-19 15:36

import datetime
import json
import os

from django.db import migrations
from django.utils import timezone
from dateutil import tz
from ..value_mappings import *


# Returns a list of the files, ignoring '.files', in the given directory
# Directory is a string of the path to the directory
def get_files(directory):
    files = os.listdir(directory)
    return [x for x in files if not (x.startswith('x'))]


def populate_hr_data(apps, schema_editor):
    directory = '../../../../../opt/data/E4/TEMP'
    files = get_files(directory)
    PhysData = apps.get_model('viz_app', 'PhysData')
    bounds = MEASUREMENT_THRESHOLDS['Heart Rate']
    for hrFile in files:
        filenameElements = hrFile.split('_')
        participant = filenameElements[0]
        frequency = filenameElements[2][:-5]
        data = json.load(open(directory + '/' + hrFile, 'r'))
        for dateString in data:
            naive_date = datetime.datetime.fromtimestamp(int(dateString)/1000)
            date = timezone.make_aware(naive_date, tz.gettz('America/New_York'))
            hr = data[dateString]
            if hr is not None and (hr < bounds[0] or hr > bounds[1]):
                hr = None
            line = PhysData(date=date,
                            category='Heart Rate',
                            interval=frequency,
                            name=participant,
                            measurement=hr)
            line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0012_auto_20180819_1450'),
    ]

    operations = [
        migrations.RunPython(populate_hr_data)
    ]
