# Generated by Django 2.0.6 on 2018-10-02 05:15

from django.db import migrations, models


def add_group(apps, schema_editor):
    PhysData = apps.get_model('viz_app', 'PhysData')
    for line in PhysData.objects.all():
        data_type = line.category
        if data_type == 'Motion' or data_type == 'Accelerometer':
            line.group = 'Activity'
        elif data_type == 'Temperature' or data_type == 'Heart Rate':
            line.group = 'Physiology'
        line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0015_auto_20180819_1607'),
    ]

    operations = [
        migrations.AddField(
            model_name='physdata',
            name='group',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.RunPython(add_group)
    ]
