# Generated by Django 2.0.6 on 2018-10-19 06:26

from django.db import migrations

def change_name_Phone_Usage(apps, schema_editor):
    PhysData = apps.get_model("viz_app", "PhysData")
    for line in PhysData.objects.filter(group='Phone Usage'):
        line.group = 'Phone_Usage'
        line.save()

class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0018_auto_20181018_2022'),
    ]

    operations = [
        migrations.RunPython(change_name_Phone_Usage)
    ]
