# Generated by Django 2.0.6 on 2019-01-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0028_weatherdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatherdata',
            name='interval',
            field=models.CharField(default='24hrs', max_length=10),
        ),
    ]
