# Generated by Django 2.0.6 on 2019-02-02 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0029_weatherdata_interval'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePrivileges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'permissions': (('aggregate', 'Can view aggregate data'), ('individual', 'Can view specific individual data')),
                'managed': False,
            },
        ),
    ]
