# Generated by Django 2.0.6 on 2019-02-21 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0031_sleepdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='sleepdata',
            name='interval',
            field=models.CharField(default='10mins', max_length=10),
        ),
    ]
