# Generated by Django 2.0.6 on 2019-02-21 01:19

import datetime
import json
import os

from django.db import migrations
from django.utils import timezone
from dateutil import tz

DATE_FORMAT = '%Y-%m-%d %H'


# Returns a list of the files, ignoring '.files', in the given directory
# Directory is a string of the path to the directory
def get_files(directory):
    files = os.listdir(directory)
    return [x for x in files if not (x.startswith('.'))]


def populate_sleep_data_reported(apps, schema_editor):
    directory = '../../../../../opt/data/Phone/phone_survey'
    files = get_files(directory)
    SleepData = apps.get_model('viz_app', 'SleepData')
    for sleepFile in files:
        participant = sleepFile.split('_')[-1][:4]
        print(sleepFile)
        data = json.load(open(directory + '/' + sleepFile, 'r'))
        for day_data in data:
            for hour in range(24):
                date_string = day_data["date"] + " 0" + str(hour) if hour <= 9 else day_data["date"] + " " + str(hour)
                naive_date = datetime.datetime.strptime(date_string, DATE_FORMAT)
                date = timezone.make_aware(naive_date, tz.gettz('America/New_York'))

                sleepLog = day_data["sleepLog"]
                if sleepLog is not None:
                    sleep_flag = sleepLog[hour]
                    if sleep_flag == 2:
                        is_asleep = True
                    else:
                        is_asleep = False
                else:
                    is_asleep = None

                line = SleepData(name=participant,
                                 date=date,
                                 category="Self-reported Sleep",
                                 is_asleep=is_asleep,
                                 interval="1hr")
                line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0032_sleepdata_interval'),
    ]

    operations = [
        migrations.RunPython(populate_sleep_data_reported)
    ]
