# Generated by Django 2.0.6 on 2019-03-29 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0035_auto_20190329_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='sex',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=7),
        ),
        migrations.AlterField(
            model_name='demographicdata',
            name='study_group',
            field=models.CharField(choices=[('MDD', 'Major Depressive Disorder'), ('HC', 'Healthy Control')], max_length=7),
        ),
    ]
