# Generated by Django 2.0.6 on 2019-04-13 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0036_auto_20190329_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographicdata',
            name='ethnicity',
            field=models.CharField(choices=[('hispanic', 'Hispanic or Latino'), ('non-hispanic', 'Non-Hispanic or Latino')], max_length=50),
        ),
    ]
