# Generated by Django 2.0.6 on 2019-04-13 20:51

from django.db import migrations


def fix_motion_hourly(apps, schema_editor):
    PhysData = apps.get_model('viz_app', 'PhysData')
    for line in PhysData.objects.filter(category='Motion', interval='1hr'):
        if line.measurement is not None:
            line.measurement = line.measurement/24
            line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0038_auto_20190413_1645'),
    ]

    operations = [
        migrations.RunPython(fix_motion_hourly),
    ]
