# Generated by Django 2.0.6 on 2019-02-21 00:45

import datetime
import json
import os

from django.db import migrations, models
from django.utils import timezone
from dateutil import tz
from ..value_mappings import *


# Returns a list of the files, ignoring '.files', in the given directory
# Directory is a string of the path to the directory
def get_files(directory):
    files = os.listdir(directory)
    return [x for x in files if not (x.startswith('.'))]


def populate_sleep_data(apps, schema_editor):
    directory = 'data/E4/NEWER_SLEEP'
    files = get_files(directory)
    SleepData = apps.get_model('viz_app', 'SleepData')
    for sleepFile in files:
        participant = sleepFile[:4]
        data = json.load(open(directory + '/' + sleepFile, 'r'))['sleep_category']
        for dateString in data:
            naive_date = datetime.datetime.fromtimestamp(int(dateString)/1000)
            date = timezone.make_aware(naive_date, tz.gettz('America/New_York'))
            sleep_integer = data[dateString]
            is_asleep = None if sleep_integer == -1 else bool(sleep_integer)
            line = SleepData(name=participant,
                             date=date,
                             category="Recorded Sleep",
                             is_asleep=is_asleep)
            line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0046_auto_20190608_1506'),
    ]

    operations = [
        migrations.RunPython(populate_sleep_data)
    ]
