# Generated by Django 2.0.6 on 2019-05-01 02:15

import pandas as pd
from django.db import migrations, models
import datetime

from django.utils import timezone

from ..value_mappings import PARTICIPANTS


def populate_sleep_regularity_data(apps, schema_editor):
    # file = 'data/Sleep/daily_sleep.csv'
    file = 'data/NewSleep/daily_sleep.csv'
    participants = set(PARTICIPANTS)
    SleepData = apps.get_model('viz_app', 'SleepData')
    df = pd.read_csv(file, usecols=['date',
                                    'ID',
                                    'sleep_reg_index'])

    for index, row in df.iterrows():
        name = row['ID']
        if name in participants:
            print(name)
            month, day, year = row['date'].split("/")
            month = "0" + month if len(month) < 2 else month
            day = "0" + day if len(day) < 2 else day
            date = "20"+ year + "-" + month + "-" + day
            regularity = row['sleep_reg_index']
            line = SleepData(name=name,
                             date=date,
                             category='Sleep Regularity',
                             interval='24hrs',
                             regularity=regularity)
            line.save()


class Migration(migrations.Migration):

    dependencies = [
        ('viz_app', '0048_auto_20190610_2305'),
    ]

    operations = [
        migrations.RunPython(populate_sleep_regularity_data)
    ]
